#!/bin/bash

cp base.h ../VimanaArduino
cp codeparser.h ../VimanaArduino
cp contextlist_gen.h ../VimanaArduino
cp gc_refcount.h ../VimanaArduino
cp gurumeditation_gen.h ../VimanaArduino
cp interp.h ../VimanaArduino
cp item.h ../VimanaArduino
cp itemlist_gen.h ../VimanaArduino
cp itemlist.h ../VimanaArduino
cp print.h ../VimanaArduino
cp primfuns_gen.h ../VimanaArduino
cp list.h ../VimanaArduino
cp string_gen.h ../VimanaArduino
cp string.h ../VimanaArduino
cp vimana.h ../VimanaArduino
cp vobj.h ../VimanaArduino
